=== bgabesz1/CRC7FC_XMLGyak/crc7fc_10.12/BG_konyv1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="qualified" elementFormDefault="qualified">
  <xs:element name="könyvek" type="könyvekType"/>
  <xs:complexType name="szereplőType">
    <xs:sequence>
      <xs:element type="xs:string" name="név"/>
      <xs:element type="xs:string" name="barátja"/>
      <xs:element type="xs:string" name="született"/>
      <xs:element type="xs:string" name="jellemzés"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="másikszereplőType">
    <xs:sequence>
      <xs:element type="xs:string" name="név"/>
      <xs:element type="xs:string" name="született"/>
      <xs:element type="xs:string" name="jellemzés"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="könyvType">
    <xs:sequence>
      <xs:element type="xs:string" name="cím"/>
      <xs:element type="xs:string" name="szerző"/>
      <xs:element type="szereplőType" name="szereplő"/>
      <xs:element type="másikszereplőType" name="másikszereplő"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="isbn"/>
  </xs:complexType>
  <xs:complexType name="könyvekType">
    <xs:sequence>
      <xs:element type="könyvType" name="könyv"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== bgabesz1/CRC7FC_XMLGyak/crc7fc_10.12/BG_konyv1.xml
<?xml version="1.0" encoding="UTF-8"?>
<könyvek xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="BG_konyv1.xsd">
    <könyv isbn="asd123">
        <cím>Best figths ever</cím>
        <szerző>Petőfi Sándor</szerző>
        <szereplő>
             <név>Baranyi Gábor</név>
            <barátja>Natasha Fireblade</barátja>
            <született>2001.03.22</született>
            <jellemzés>Erős, menő</jellemzés>
        </szereplő>
        <másikszereplő>
            <név>Natasha Fireblade</név>
            <született>2002.10.20</született>
            <jellemzés>Cuki, erős</jellemzés>
        </másikszereplő>
    </könyv>
</könyvek>
