=== bgabesz1/CRC7FC_XMLGyak/crc7fc_10.12/BG_orarend1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="qualified" elementFormDefault="qualified" >
  <xs:element name="napok" type="napokType"/>
  <xs:complexType name="idopontType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="nap" use="required"/>
        <xs:attribute type="xs:string" name="tol" use="required"/>
        <xs:attribute type="xs:string" name="ig" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="oraType">
    <xs:sequence>
      <xs:element type="xs:string" name="targy"/>
      <xs:element type="idopontType" name="idopont"/>
      <xs:element type="xs:string" name="helyszin"/>
      <xs:element type="xs:string" name="oktato"/>
      <xs:element type="xs:string" name="szak"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="id" use="required"/>
    <xs:attribute type="xs:string" name="típus" use="required"/>
  </xs:complexType>
  <xs:complexType name="hétfőType">
    <xs:sequence>
      <xs:element type="oraType" name="ora" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="keddType">
    <xs:sequence>
      <xs:element type="oraType" name="ora" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="szerdaType">
    <xs:sequence>
      <xs:element type="oraType" name="ora" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="csütörtökType">
    <xs:sequence>
      <xs:element type="oraType" name="ora"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="napokType">
    <xs:sequence>
      <xs:element type="hétfőType" name="hétfő"/>
      <xs:element type="keddType" name="kedd"/>
      <xs:element type="szerdaType" name="szerda"/>
      <xs:element type="csütörtökType" name="csütörtök"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== bgabesz1/CRC7FC_XMLGyak/crc7fc_10.12/BG_orarend1.xml
<?xml version="1.0" encoding="UTF-8"?>

<napok xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="BG_orarend1.xsd">
<hétfő>
    <ora id="GEMAK131-B" típus="ELmélet">
    <targy>Valószinűség-számítás és matematikai statisztika</targy>
    <idopont nap="hétfő" tol="8" ig="10"/>
    <helyszin>218.terem</helyszin>
    <oktato>Dr. Fegyverneki Sándor</oktato>
    <szak>Matematika</szak>
    </ora>
    <ora id="GEIAL333-B" típus="ELmélet">
    <targy>Web-es alkalmazások</targy>
    <idopont nap="hétfő" tol="10" ig="12"/>
    <helyszin>info ep. 101.terem</helyszin>
    <oktato>Dr. Krizsán Zoltán</oktato>
    <szak>Informatika</szak>
    </ora>
    <ora id="GEIAL331-B" típus="ELmélet">
    <targy>Web technológiák 1</targy>
    <idopont nap="hétfő" tol="12" ig="14"/>
    <helyszin>305.terem</helyszin>
    <oktato>Agárdi Anita</oktato>
    <szak>Informatika</szak>
    </ora>
    <ora id="GEIAK130-B" típus="ELmélet">
    <targy>Mesterséges intelligencia alapok</targy>
    <idopont nap="hétfő" tol="14" ig="17"/>
    <helyszin>XXXII.előadó</helyszin>
    <oktato>Dr. Dudás László</oktato>
    <szak>Informatika</szak>
    </ora>
    <ora id="GEIAL331-B" típus="Gyakorlat">
    <targy>Web technológiák 1</targy>
    <idopont nap="hétfő" tol="17" ig="19"/>
    <helyszin>info ep. 101.terem</helyszin>
    <oktato>Agárdi Anita</oktato>
    <szak>Informatika</szak>
    </ora>

</hétfő>
<kedd>
    <ora id="GEIAL333-B" típus="Gyakorlat">
    <targy>Web-es alkalmazások</targy>
    <idopont nap="hétfő" tol="10" ig="12"/>
    <helyszin>info ep. 101.terem</helyszin>
    <oktato>Dr. Krizsán Zoltán</oktato>
    <szak>Informatika</szak>
    </ora>
    <ora id="GEIAL332-B" típus="ELmélet">
    <targy>Adatkezelés XML-ben</targy>
    <idopont nap="hétfő" tol="12" ig="14"/>
    <helyszin>I.előadó</helyszin>
    <oktato>Bednarik László</oktato>
    <szak>Informatika</szak>
    </ora>
    <ora id="GEIAL332-B" típus="Gyakorlat">
    <targy>Adatkezelés XML-ben</targy>
    <idopont nap="hétfő" tol="14" ig="16"/>
    <helyszin>info ep. 103.terem</helyszin>
    <oktato>Bednarik László</oktato>
    <szak>Informatika</szak>
    </ora>
    <ora id="GEIAK130-B" típus="Gyakorlat">
    <targy>Mesterséges intelligencia alapok</targy>
    <idopont nap="hétfő" tol="18" ig="19"/>
    <helyszin>info ep. 15.terem</helyszin>
    <oktato>Dr. Dudás László</oktato>
    <szak>Informatika</szak>
    </ora>
</kedd>
<szerda>
    <ora id="GEIAL31H-B" típus="Elmélet">
    <targy>Szoftvertesztelés</targy>
    <idopont nap="hétfő" tol="8" ig="10"/>
    <helyszin>info ep. 103.terem</helyszin>
    <oktato>Tompa Tamás</oktato>
    <szak>Informatika</szak>
    </ora>
    <ora id="GEIAL31H-B" típus="Gyakorlat">
    <targy>Szoftvertesztelés</targy>
    <idopont nap="hétfő" tol="10" ig="12"/>
    <helyszin>info ep. 103.terem</helyszin>
    <oktato>Tompa Tamás</oktato>
    <szak>Informatika</szak>
    </ora>
    <ora id="GEIAK120-B" típus="Elmélet">
    <targy>Integrált vállalati rendszerek</targy>
    <idopont nap="hétfő" tol="14" ig="16"/>
    <helyszin>14.terem</helyszin>
    <oktato>Dr. Dadvandipour Samad</oktato>
    <szak>Informatika</szak>
    </ora>
    <ora id="GEIAK120-B" típus="Gyakorlat">
    <targy>Integrált vállalati rendszerek</targy>
    <idopont nap="hétfő" tol="16" ig="18"/>
    <helyszin>info ep. 15.terem</helyszin>
    <oktato>Dr. Kulcsárné Dr. Forrai Mónika</oktato>
    <szak>Informatika</szak>
    </ora>
</szerda>
<csütörtök>
    <ora id="GEMAK131-B" típus="Gyakorlat">
    <targy>Valószinűség-számítás és matematikai statisztika</targy>
    <idopont nap="hétfő" tol="10" ig="12"/>
    <helyszin>309.terem</helyszin>
    <oktato>Dr. Glavosits Tamás</oktato>
    <szak>Matematika</szak>
    </ora>
</csütörtök>
</napok>
