=== bgabesz1/CRC7FC_XMLGyak/crc7fc_09.28/BG_konyv.dtd
<?xml version="1.0" encoding="UTF-8"?>

	<!ELEMENT konyvek (konyv*)>
	<!ELEMENT konyv (cím, kiadásiev, kiado, szerzo+)>
		<!ATTLIST konyv id ID #REQUIRED>
		<!ELEMENT cím (#PCDATA)>
		<!ELEMENT kiadásiev (#PCDATA)>
		<!ELEMENT kiado (#PCDATA)>
		<!ELEMENT szerzo (#PCDATA)>

=== bgabesz1/CRC7FC_XMLGyak/crc7fc_09.28/BG_konyv.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE konyvek SYSTEM "BG_konyv.dtd">
<konyvek>
    <konyv id="asdfy">
        <cím>Excel 2019</cím>
        <kiadásiev>2021</kiadásiev>
        <kiado>TARAMIX Kiadó Kft. </kiado>
        <szerzo>Szabó Ildikó</szerzo>
    </konyv>
    <konyv id="yxckmna">
        <cím>Szövegbányászat és mesterséges intelligencia R-ben</cím>
        <kiadásiev>2021</kiadásiev>
        <kiado>Typotex Elektronikus Kiadó Kft.</kiado>
        <szerzo> Máté Ákos</szerzo>
        <szerzo>Ring Orsolya</szerzo>
        <szerzo>Sebők Miklós </szerzo>
    </konyv>
    <konyv id="akpmac">
        <cím>Word 2019</cím>
        <kiadásiev>2021</kiadásiev>
        <kiado>TARAMIX Kiadó Kft. </kiado>
        <szerzo>Dávid Krisztina</szerzo>
    </konyv>
</konyvek>

=== bgabesz1/CRC7FC_XMLGyak/crc7fc_10.05/konyvek/BG_konyv.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE konyvek SYSTEM "BG_konyv.dtd">
<konyvek xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="BG_konyv.xsd">
    <konyv id="asdfy">
        <cím>Excel 2019</cím>
        <kiadásiev>2021</kiadásiev>
        <kiado>TARAMIX Kiadó Kft.</kiado>
        <szerzo>Szabó Ildikó</szerzo>
        <abstract>Informatikai könyv</abstract>
    </konyv>
    <konyv id="yxckmna">
        <cím>Szövegbányászat és mesterséges intelligencia R-ben</cím>
        <kiadásiev>2021</kiadásiev>
        <kiado>Typotex Elektronikus Kiadó Kft.</kiado>
        <szerzo>Máté Ákos</szerzo>
        <szerzo>Ring Orsolya</szerzo>
        <szerzo>Sebők Miklós</szerzo>
        <abstract>Informatikai könyv</abstract>
    </konyv>
    <konyv id="akpmac">
        <cím>Word 2019</cím>
        <kiadásiev>2021</kiadásiev>
        <kiado>TARAMIX Kiadó Kft.</kiado>
        <szerzo>Dávid Krisztina</szerzo>
        <abstract>Informatikai könyv</abstract>
    </konyv>
    
</konyvek>
