=== bgabesz1/CRC7FC_XMLGyak/xml_gyak_09.28/BG_ertodtd.DTD
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE minta [ <!ELEMENT Acd (#PCDATA)>

<!ELEMENT minta <!ELEMENT Ace (#PCDATA)>
(A*, B*, C*, A_B*)> |] <!ELEMENT B (Bb)>

<!ELEMENT A (Ab*, Ac)> 
<!ATTLIST A Aa ID #REQUIRED> | 
<!ELEMENT Ab (Abx, Aby)> 
<!ELEMENT Abx (#PCDATA)> 
<!ELEMENT Aby (#PCDATA)> 
<!ELEMENT Ac (Acd, Ace)>
<!ATTLIST B Ba ID #REQUIRED>
<!ATTLIST B Bc IDREF #IMPLIED>
<!ELEMENT Bb (Bbx, Bby)>
<!ELEMENT Bbx (#PCDATA)>
<!ELEMENT Bby (#PCDATA)>
 <!ELEMENT C (Cb)>
<!ATTLIST C Ca ID #REQUIRED>
<!ELEMENT Cb (#PCDATA)>
<!ELEMENT A_B (A_Bc)>
<!ATTLIST A_B A_B_a IDREF #IMPLIED>
<!ATTLIST A_B A_B_b IDREF #IMPLIED>
<!ELEMENT A_Bc (#PCDATA)>
]>

=== bgabesz1/CRC7FC_XMLGyak/crc7fc_09.28/BG_dtdtoxml.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE minta SYSTEM "BG_ertodtd.dtd">
<minta>
    <A Aa="ACSA">
        <Ac>
            <Acd></Acd>
            <Ace></Ace>
        </Ac>
    </A>
    <B Ba="YCVA">
        <Bb>
            <Bbx></Bbx>
            <Bby></Bby>
        </Bb>
    </B>
    <C Ca="ADS">
        <Cb></Cb>
    </C>
    <A_B>
        <A_Bc></A_Bc>
    </A_B>
</minta>
