=== bgabesz1/CRC7FC_XMLGyak/crc7fc_10.19/macskakCRC7FC.dtd
<?xml version="1.0" encoding="UTF-8"?>
        <!ELEMENT macskak (macska)*>
        <!ELEMENT macska (macskaid)*>
        <!ELEMENT macskaid (nev|kor|fajta)*>
        <!ELEMENT nev (#PCDATA)>
        <!ELEMENT kor (#PCDATA)>
        <!ELEMENT fajta (#PCDATA)>

=== bgabesz1/CRC7FC_XMLGyak/crc7fc_10.19/macskakCRC7FC.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE macskak SYSTEM "macskakCRC7FC.dtd">
<macskak xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="macskakCRC7FC.xsd">
    <macska>
        <macskaid>
            <nev>Mihály</nev>
            <kor>10 év</kor>
            <fajta>UV</fajta>
        </macskaid>
        <macskaid>
            <nev>Leo</nev>
            <kor>3 év</kor>
            <fajta>Perzsa</fajta>
        </macskaid>
        <macskaid>
            <nev>Miki</nev>
            <kor>1 év</kor>
            <fajta>Sziámi</fajta>
        </macskaid>
    </macska>
</macskak>

=== bgabesz1/CRC7FC_XMLGyak/crc7fc_10.19/SaxCRC7FC/SaxCRC7FC/bin/SaxCRC7FC1020/macskakCRC7FC.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE macskak SYSTEM "macskakCRC7FC.dtd">
<macskak xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="macskakCRC7FC.xsd">
        <macska id="M1">
            <nev>Mihály</nev>
            <kor>10 év</kor>
            <fajta>UV</fajta>
        </macska>
        <macska id="M2">
            <nev>Leo</nev>
            <kor>3 év</kor>
            <fajta>Perzsa</fajta>
        </macska>
        <macska id="M2">
            <nev>Miki</nev>
            <kor>1 év</kor>
            <fajta>Sziámi</fajta>
        </macska>
</macskak>
